<a href="https://colab.research.google.com/github/msharma1207/usingLSTM_for_fake_news_detection/blob/main/usingLSTM_for_fake_news_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


In [ ]:
df=pd.read_csv('train.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']


In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [ ]:
### Vocabulary size
voc_size=5000


**Onehot** **Representation**

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:


### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)



Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2789, 930, 702, 43, 4661, 2936, 1009, 600, 279, 1336],
 [4476, 337, 2605, 3609, 219, 4663, 4966],
 [1166, 3350, 4571, 1877],
 [4508, 1546, 565, 4418, 678, 117],
 [3658, 219, 3420, 4668, 1126, 3749, 219, 3379, 2579, 1040],
 [1342,
  1216,
  2977,
  4500,
  389,
  2478,
  2796,
  4788,
  3517,
  1113,
  3269,
  2700,
  1074,
  4003,
  4966],
 [988, 4747, 4684, 3050, 3796, 3497, 2092, 2124, 684, 558, 4240],
 [1913, 1961, 2946, 1566, 78, 754, 2478, 534, 684, 558, 4240],
 [4472, 297, 4983, 3367, 2812, 2974, 465, 1770, 2478, 3402],
 [1831, 1414, 3610, 93, 833, 1629, 4438, 4256],
 [607, 1669, 3127, 1331, 4823, 2119, 2310, 4854, 935, 2182, 1018],
 [4418, 2827, 4661, 2974, 2478, 78],
 [1249, 1647, 4058, 4126, 3943, 2468, 1622, 3988, 305],
 [4861, 2726, 786, 2160, 2713, 2102, 4586, 684, 558, 4240],
 [744, 3065, 3238, 4089, 1691, 684, 558, 4240],
 [4466, 391, 2464, 2520, 4818, 4515, 1968, 4188, 2885, 1438],
 [4382, 3581, 337],
 [3720, 3469, 3169, 1599, 2478, 4448, 1701, 4966],
 [1195, 4150, 260


**Embedding Representation**

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  600  279 1336]
 [   0    0    0 ...  219 4663 4966]
 [   0    0    0 ... 3350 4571 1877]
 ...
 [   0    0    0 ...  684  558 4240]
 [   0    0    0 ... 2533 1663 2062]
 [   0    0    0 ...  163  494 2645]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2789,
        930,  702,   43, 4661, 2936, 1009,  600,  279, 1336], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())


Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_7 (LSTM)               (None, 100)               56400     
                                                                 
 dense_7 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)


**Model Training**

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=15,batch_size=64)

Epoch 1/15
192/192 [==============================] - 6s 22ms/step - loss: 0.3539 - accuracy: 0.8310 - val_loss: 0.2131 - val_accuracy: 0.9153
Epoch 2/15
192/192 [==============================] - 4s 19ms/step - loss: 0.1426 - accuracy: 0.9423 - val_loss: 0.1918 - val_accuracy: 0.9225
Epoch 3/15
192/192 [==============================] - 4s 19ms/step - loss: 0.0943 - accuracy: 0.9633 - val_loss: 0.2268 - val_accuracy: 0.9238
Epoch 4/15
192/192 [==============================] - 4s 21ms/step - loss: 0.0629 - accuracy: 0.9782 - val_loss: 0.2469 - val_accuracy: 0.9090
Epoch 5/15
192/192 [==============================] - 4s 19ms/step - loss: 0.0428 - accuracy: 0.9851 - val_loss: 0.3324 - val_accuracy: 0.9218
Epoch 6/15
192/192 [==============================] - 4s 19ms/step - loss: 0.0232 - accuracy: 0.9938 - val_loss: 0.4113 - val_accuracy: 0.9130
Epoch 7/15
192/192 [==============================] - 4s 21ms/step - loss: 0.0149 - accuracy: 0.9959 - val_loss: 0.3946 - val_accuracy: 0.9142

In [ ]:
y_pred=model.predict(X_test)
y_pred = np.round(y_pred).astype(int)

**Adding Dropout**

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.1))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

**Performance Metrics And Accuracy**

In [ ]:
y_pred=model.predict(X_test)
y_pred = np.round(y_pred).astype(int)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[3139,  280],
       [ 265, 2351]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.9096934548467275